# Generated by Django 5.2.7 on 2025-11-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_bio_profile_facebook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linkedın',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='linkedın_username',
            new_name='linkedin_username',
        ),
    ]
