# Generated by Django 5.2.7 on 2025-11-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_commentlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_date']},
        ),
    ]
